server:
  port: 7003

eureka:
  instance:
    hostname: eurka7003
  client:
    register-with-eureka: false
    fetch-registry: false # 注册中心
    service-url: #监控页面
      defaultZone: http://eurka7001:7001/eureka/,http://eurka7002:7002/eureka/
