server:
  port: 3344

spring:
  application:
    name: springcloudconfig-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/1006YL/springcloudconfig.git
